### PR TITLE
F#5 for Docs -- One Approach

### PR DESCRIPTION
**Pull request by Gastove**
This updates to F#5 for documentation. Along the way, it updates the FSFormatting tool rather considerable (from version 4 to 8). To try and make the documentation build as "standard" as possible, I've experimented with moving documentation out of `docsrc` and in to `docs/`, where `fsdocs` looks for them by default. This can be tested locally by pulling down my branch and running:

```shell
dotnet tool restore
dotnet fsdocs watch
```

This makes writing and previewing docs very simple and lightweight. However, it does _not_ solve the question of deploy automation -- which can be solved so many ways that I wanted to check in with y'all about preferences. There's also some question about project structure. I'm inclined towards:

1. Remove the current `docsrc` dir; rename `docs` to `docsrc`.
2. Configure `fsdocs` to build from `docsrc`, outputting to `docs/`
3. Configure Github to serve docs from the `docs` dir. 

For automation, this could be: a shell script; a FAKE script; an F# script mostly replicating some of the tooling currently in `docsrc`; an update to the current `docsrc` program. I'm happy to be guided by y'all. I typically default to FAKE, because I find it to be the "least surprising" thing -- but not everyone loves FAKE.

Thanks in advance!

### CODE REVIEW

**Comment by wallymathieu** [comment]
Looks like we get some issues with rendering docs that use F# Data types.

**Comment by Choc13** [comment]
What's the status on this PR? I'd like to build on top of this to address #103 (specifically to show how to write a combined `JsonObjCodec` for a DU). There are also some other improvements to the documentation that would be useful, such as providing more background on the different types of codec available in the library. 

I'm happy to get help with this PR if others are too busy as I have some time over the next few days.

**Comment by wallymathieu** [comment]
@Choc13 I've done some work in:
https://github.com/Gastove/Fleece/compare/fsharp-five-for-docs...wallymathieu:fsharp-five-for-docs?expand=1
what I do is :
```
dotnet build -c Release
dotnet run -p ./docsrc/tool ReleaseDocs
```
in order to publish to:
https://wallymathieu.github.io/Fleece/

There are some things that needs to be adjusted, perhaps fixed in F# Formatting as seen in : 

We notice that we get a lot of unfiltered types:
https://wallymathieu.github.io/Fleece/reference/fleece.html

What we would like would be to be able to filter out types from rendering in the documentation. There is this issue related to the rendering:
https://github.com/fsprojects/FSharp.Formatting/issues/647

**Comment by wallymathieu** [comment]
It also looks like the icon does not render in the reference docs.

**Comment by wallymathieu** [comment]
That some of the types gets repeated could perhaps be OK enough, we could add some xml-doc texts writing that they are internal. The icon not showing looks a bit more annoying, so would be nice to fix.

**Review by wallymathieu — APPROVED** [review]

**Review by gusty — APPROVED** [review]

**Pull request merged**
